<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="GeoTimeZone" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>
</Project>
