# tools/fixtures/make-replay-fixture.ps1
#Requires -Version 7
<#
.SYNOPSIS
  Writes tests/UasSort.Testing/Replay/library-listing.json, the golden-replay fixture (Ref §13).
  LISTING ONLY: Get-ChildItem reads names, sizes, times and attributes; no library file is ever opened,
  so cloud-only (placeholder) files are never hydrated. Run once; the output is checked in and never regenerated by tests.
#>
param(
    [string]$VideoRoot = (Join-Path ([Environment]::GetFolderPath('MyPictures')) 'UAS Videos'),
    [string]$Out = (Join-Path $PSScriptRoot '..\..\tests\UasSort.Testing\Replay\library-listing.json'),
    [string]$Calibration = (Join-Path $PSScriptRoot '..\..\docs\research\spikes\djmd\calibration.json'),
    [string]$MoreGps = (Join-Path $PSScriptRoot '..\..\docs\research\spikes\grouping\more_gps.json'),
    [string]$PcZone = 'America/Anchorage'
)
$ErrorActionPreference = 'Stop'
$inv = [Globalization.CultureInfo]::InvariantCulture
$root = (Resolve-Path -LiteralPath $VideoRoot).Path.TrimEnd('\')

function ConvertTo-UtcText($value) {
    if ($null -eq $value) { return $null }
    $utc = if ($value -is [DateTime]) { $value.ToUniversalTime() }
           else { [DateTimeOffset]::Parse([string]$value, $inv).UtcDateTime }
    return $utc.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", $inv)
}

$gps = @{}
foreach ($r in @(Get-Content -Raw -LiteralPath $Calibration | ConvertFrom-Json) + @(Get-Content -Raw -LiteralPath $MoreGps | ConvertFrom-Json)) {
    if ($null -ne $r.lat -and -not $gps.ContainsKey($r.name)) { $gps[$r.name] = $r }
}
$noMoov = @('DJI_20260727002013_0014_D.MP4', 'DJI_20260727005240_0024_D.MP4')

$entries = [System.Collections.Generic.List[object]]::new()
$clips = [ordered]@{}
$files = Get-ChildItem -LiteralPath $root -Recurse -Force -File |
    Where-Object { -not $_.FullName.StartsWith("$root\.uas-sort\", [StringComparison]::OrdinalIgnoreCase) } |
    Sort-Object { $_.FullName.Substring($root.Length + 1) }
foreach ($f in $files) {
    $rel = $f.FullName.Substring($root.Length + 1).Replace('\', '/')
    $entries.Add([ordered]@{
        relPath    = $rel
        size       = $f.Length
        mtimeUtc   = $f.LastWriteTimeUtc.ToString("yyyy-MM-dd'T'HH:mm:ss.fffffff'Z'", $inv)
        attributes = [int]$f.Attributes
    })
    if ($rel -like 'Picture Offload/*' -or $f.Extension -ne '.mp4') { continue }
    $name = $f.Name
    $clip = [ordered]@{ lat = $null; lon = $null; mvhdUtc = $null; hasMoov = $true; mvhdSimulated = $false }
    if ($name -match '^DJI_(\d{14})_') {
        $g = $gps[$name]
        if ($g) { $clip.lat = [double]$g.lat; $clip.lon = [double]$g.lon }
        if ($noMoov -contains $name) { $clip.hasMoov = $false }
        elseif ($g -and $g.mvhd_creation_utc) { $clip.mvhdUtc = ConvertTo-UtcText $g.mvhd_creation_utc }
        else {
            $stamp = [DateTime]::ParseExact($Matches[1], 'yyyyMMddHHmmss', $inv)
            $clip.mvhdUtc = $stamp.AddHours(4).ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", $inv)
            $clip.mvhdSimulated = $true
        }
    }
    $clips[$name] = $clip
}
$doc = [ordered]@{
    v           = 1
    snapshotUtc = [DateTime]::UtcNow.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", $inv)
    pcZone      = $PcZone
    entries     = $entries
    clips       = $clips
}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Out) | Out-Null
$doc | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $Out -Encoding utf8NoBOM
Write-Host "Wrote $($entries.Count) entries and $($clips.Count) clips to $Out"
