<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.9" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageVersion Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
    <PackageVersion Include="WinUI.TableView" Version="1.5.0" />
    <PackageVersion Include="MetadataExtractor" Version="2.9.3" />
    <PackageVersion Include="GeoTimeZone" Version="6.1.0" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.12" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.1" />
  </ItemGroup>
</Project>
